name: cinemapedia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  flutter_dotenv: ^5.1.0
  dio: ^5.4.1
  flutter_riverpod: ^2.4.10
  card_swiper: ^3.0.1
  animate_do: ^3.3.3
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: ^2.3.10
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#6699FF"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-1.jpeg"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
    - assets/loaders/


